name: kyle
favicon: null
layout_spectrum: 0.65734
typography_spectrum: 0.0174344836268574
title: The Kyle Grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdffc3'
    - '#030025'
    - '#f17f46'
    - '#ff0000'
    - '#2b7466'
  brandStrength: 0.625
  lightness: 0.3125
  saturation: 0.7564757955260575
  rhythmicContrast: 0.6081062769517303
purpose: []
