name: kyle
favicon: null
layout_spectrum: 0.9393598076421767
typography_spectrum: 0.0174344836268574
title: The Kyle Grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6332242405042052
  lightness: 0.30065738572739065
  saturation: 0.7564757955260575
  rhythmicContrast: 0.6081062769517303
purpose: []
